### ISSUE TITLE
error executing FindTransactionsByAccountId  query

### ISSUE THREAD

**Issue by matisalimbene** [hyperledger/iroha-javascript#184]
I'm unable to execute the `FindTransactionsByAccountId` query. I wasn't able to find any similar example for follow on how to construct the query. (Tests use the sugar library).

```js
const getTxLog = async (accountId) => {

  const {
    AccountId,
    QueryBox,
    Expression,
    Value,
    IdBox,
  } = datamodel;
  const [accName, accDomainId] = accountId.split('@');
  const accDefId = sugar.accountId(accName, accDomainId);

  const account = AccountId({
    name: accName,
    domain_id: accDomainId,
  });

  cons query = QueryBox('FindTransactionsByAccountId', {
    account_id: Expression('Raw', Value('Id', IdBox('AccountId', account))),
  });

  const { pre, client } = _clientFactory();
  const result = await client.requestWithQueryBox(pre, query);
  return { data: result };
};
```

Right now this is the err I'm getting:
```log
Cannot read properties of undefined (reading 'length')
```

These are the documentation Links I followed:

- https://hyperledger.github.io/iroha-2-docs/guide/get-started/javascript.html#_7-querying-for-domains-accounts-and-assets
- https://hyperledger.github.io/iroha-2-docs/reference/queries.html#findtransactionsbyaccountid

**Comment by 0x009922** [comment]
The issue is that you are constructing the account id incorrectly:

```ts
const getTxLog = async (accountId) => {  
  // ...

  const [accName, accDomainId] = accountId.split('@');  
  
  const account = AccountId({  
    name: accName,  
    domain_id: accDomainId,
    //         ^^^^^^^^^^^ - got `string`, expected `DomainId`
  });

  // ...
}
```

When codec tries to encode the `domain_id` field, it passes the `domain_id.name` field into a String codec, which looks up for a `.length` field, and that's where you get the

```
Cannot read properties of undefined (reading 'length')
```

error.

So, the fix would be to construct a proper `DomainId`:

```ts
const account = AccountId({  
  name: accName,  
  domain_id: datamodel.DomainId({ name: accDomainId })  
})
```

**Once again, I strongly recommend you using TypeScript, because this error can be easily caught using its diagnostics.** For example, if you annotate the `accountId` argument with `string` type, TypeScript highlights the error:


```ts
const getTxLog = async (accountId: string) => {  
  //                             ^^^^^^^^ add this

  // ...
  
  const account = AccountId({  
    name: accName,  
    domain_id: accDomainId,
//  ^^^^^^^^^ TS2322: Type string is not assignable to type DomainId
  });

  // ...
}
```
